### ISSUE TITLE
karotz.snapshot_ftp

### ISSUE THREAD

**Issue by noog** [guillaumewuip/openkarotz-nodejs#1]
i have this error when i use karotz.snapshot_ftp

var server_url = 'xxx';
var server_pwd = 'xxxx';
var remote_dir = '';
karotz.snapshot_ftp(server_url, server_url,server_pwd,remote_dir, function(error, msg) {
    console.log(error); //false
    console.log(msg); //return json from the api
})

ERROR => 
{ msg: 'Request error', status: undefined }
false
{ return: '1',
  msg: 'Missing mandatory parameter : (remote_dir)' }

**Comment by guillaumewuip** [comment]
Hi,

Thanks, Iit seems it's a bug. The `snapshot_ftp` function doesn't send the good parameters to the rabbit. By the way, you've forgotten the `user` param.

I'll push a fix asap

**Comment by guillaumewuip** [comment]
Ok, so the `1.1.5` which is just publish on npm should fix the bug. Notice that I've added the `silent` param : 

``` js

var karotz = new .... ; 

karotz.snapshot_ftp("192.168.0.1", "toto", "000", "~", false, callback);

```

Let me know if everything is ok :)

**Comment by noog** [comment]
hello

the upload is ok :)
thank you
your code is on my raspberry pi

**Comment by noog** [comment]
is it possible to detect a rfid object ?
what is the command ?

**Comment by guillaumewuip** [comment]
Fine.
For the RFID pb, it's possible but not on the Node side. Use the Openkarotz api web app to listen to the RFID tag and to something (call url by example)

**Comment by noog** [comment]
hello

the response off the call back is

true
{ msg: 'Request error', status: undefined }

for

console.log(error); //false
console.log(msg); //return json from the api

is it possible to have the filename of the newsnapshot in the callback 
(in msg) ?

thanks

**Comment by guillaumewuip** [comment]
Hi @noog 
If the response is an error, it's really an error. When doing some tests last day, I found a lot of errors but the picture was well send to the ftp each time.
It was in fact the HTTP headers that was corrupted by something the rabbit send (maybe a log from the snapshot). So it's a problem from openkarotz.

If everything is ok, it should return : `{filename: "....png", result : "0"}`

**Comment by noog** [comment]
ok

is it the right syntax

karotz.snapshot_ftp("xxxx", "xxxxx", "xxxx", "~", false, 
function(error,msg) {
     console.log(error); //false
     console.log(msg); //return json from the api
         console.log(response);
});

**Comment by guillaumewuip** [comment]
yes, except that I don't see what `console.log(response)` will output as there is no `response` var here.
